# Categorical variable encoding

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
#load dataset 
data_path = r'E:\machine_learning_practice\practice\machine_learning_handson\data\tips.csv'

tips_df = pd.read_csv(data_path)
tips_df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
pd.get_dummies(tips_df, columns=['sex', 'smoker', 'day', 'time'], drop_first=True)

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16.99,1.01,2,False,False,False,True,False,False
1,10.34,1.66,3,True,False,False,True,False,False
2,21.01,3.50,3,True,False,False,True,False,False
3,23.68,3.31,2,True,False,False,True,False,False
4,24.59,3.61,4,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,True,False,True,False,False,False
240,27.18,2.00,2,False,True,True,False,False,False
241,22.67,2.00,2,True,True,True,False,False,False
242,17.82,1.75,2,True,False,True,False,False,False
243,18.78,3.00,2,False,False,False,False,True,False

In [8]:
dummy_df = pd.get_dummies(tips_df)
dummy_df

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,16.99,1.01,2,True,False,True,False,False,False,True,False,True,False
1,10.34,1.66,3,False,True,True,False,False,False,True,False,True,False
2,21.01,3.50,3,False,True,True,False,False,False,True,False,True,False
3,23.68,3.31,2,False,True,True,False,False,False,True,False,True,False
4,24.59,3.61,4,True,False,True,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,False,True,True,False,False,True,False,False,True,False
240,27.18,2.00,2,True,False,False,True,False,True,False,False,True,False
241,22.67,2.00,2,False,True,False,True,False,True,False,False,True,False
242,17.82,1.75,2,False,True,True,False,False,True,False,False,True,False
243,18.78,3.00,2,True,False,True,False,False,False,False,True,True,False

In [9]:
dummy_df = pd.get_dummies(tips_df, drop_first=True)
dummy_df

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16.99,1.01,2,False,False,False,True,False,False
1,10.34,1.66,3,True,False,False,True,False,False
2,21.01,3.50,3,True,False,False,True,False,False
3,23.68,3.31,2,True,False,False,True,False,False
4,24.59,3.61,4,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,True,False,True,False,False,False
240,27.18,2.00,2,False,True,True,False,False,False
241,22.67,2.00,2,True,True,True,False,False,False
242,17.82,1.75,2,True,False,True,False,False,False
243,18.78,3.00,2,False,False,False,False,True,False

# one hot encoding with sklearn

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
oh_enc = OneHotEncoder(sparse_output=False,drop='first')

In [20]:
oh_enc_arr = oh_enc.fit_transform(tips_df[['sex', 'smoker', 'day', 'time']])
oh_enc_arr

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       ...,
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], shape=(244, 6))

In [21]:
oh_enc_df = pd.DataFrame(oh_enc_arr, columns=oh_enc.get_feature_names_out(['sex', 'smoker', 'day', 'time']))
oh_enc_df

     sex_Male  smoker_Yes  day_Sat  day_Sun  day_Thur  time_Lunch
0         0.0         0.0      0.0      1.0       0.0         0.0
1         1.0         0.0      0.0      1.0       0.0         0.0
2         1.0         0.0      0.0      1.0       0.0         0.0
3         1.0         0.0      0.0      1.0       0.0         0.0
4         0.0         0.0      0.0      1.0       0.0         0.0
..        ...         ...      ...      ...       ...         ...
239       1.0         0.0      1.0      0.0       0.0         0.0
240       0.0         1.0      1.0      0.0       0.0         0.0
241       1.0         1.0      1.0      0.0       0.0         0.0
242       1.0         0.0      1.0      0.0       0.0         0.0
243       0.0         0.0      0.0      0.0       1.0         0.0

[244 rows x 6 columns]

In [22]:
final_df = pd.concat([tips_df[['total_bill', 'tip', 'size']], oh_enc_df], axis=1)
final_df

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16.99,1.01,2,0.0,0.0,0.0,1.0,0.0,0.0
1,10.34,1.66,3,1.0,0.0,0.0,1.0,0.0,0.0
2,21.01,3.50,3,1.0,0.0,0.0,1.0,0.0,0.0
3,23.68,3.31,2,1.0,0.0,0.0,1.0,0.0,0.0
4,24.59,3.61,4,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,1.0,0.0,1.0,0.0,0.0,0.0
240,27.18,2.00,2,0.0,1.0,1.0,0.0,0.0,0.0
241,22.67,2.00,2,1.0,1.0,1.0,0.0,0.0,0.0
242,17.82,1.75,2,1.0,0.0,1.0,0.0,0.0,0.0
243,18.78,3.00,2,0.0,0.0,0.0,0.0,1.0,0.0